/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.xyz.roemahduren.presentation.screen;

import com.xyz.roemahduren.presentation.component.RoundedButton;
import com.xyz.roemahduren.presentation.component.input.RoundedTextArea;
import com.xyz.roemahduren.presentation.component.input.RoundedTextField;
import com.xyz.roemahduren.presentation.component.panel.RoundedPanel;
import com.xyz.roemahduren.presentation.component.table.Table;
import com.xyz.roemahduren.presentation.component.table.TableActionCellRender;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 * @author user
 */

public class BranchScreen extends JPanel {

    /**
     * Creates new form BranchScreen
     */

    public BranchScreen() {
        initComponents();


        branchTable.getColumnModel().getColumn(3).setCellRenderer(new TableActionCellRender());
        taAddress.fixArea(scrollAddressTextArea);
        branchTable.fixTable(scrollBranchTable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formPanel = new RoundedPanel();
        branchNameLabel = new JLabel();
        addressLabel = new JLabel();
        tfBranchName = new RoundedTextField();
        errorBranchNameLabel = new JLabel();
        scrollAddressTextArea = new JScrollPane();
        taAddress = new RoundedTextArea();
        errorAddressLabel = new JLabel();
        btnSave = new RoundedButton();
        btnCancel = new RoundedButton();
        scrollBranchTable = new JScrollPane();
        branchTable = new Table();
        branchListTitle = new JLabel();
        tfSearch = new RoundedTextField();
        searchBtn = new RoundedButton();
        titleLabel = new JLabel();

        setBackground(new Color(255, 255, 255));
        setPreferredSize(new Dimension(800, 800));
        setSize(new Dimension(800, 800));

        formPanel.setBackground(new Color(243, 244, 245));
        formPanel.setForeground(new Color(95, 108, 123));
        formPanel.setCornerRadius(8);

        branchNameLabel.setForeground(new Color(95, 108, 123));
        branchNameLabel.setText("Branch Name");

        addressLabel.setForeground(new Color(95, 108, 123));
        addressLabel.setText("Address");

        tfBranchName.setFont(new Font("Helvetica Neue", 0, 14)); // NOI18N
        tfBranchName.setPlaceholder("Contoh: Jakarta");

        errorBranchNameLabel.setForeground(new Color(220, 53, 69));

        taAddress.setColumns(20);
        taAddress.setRows(5);
        taAddress.setFont(new Font("Helvetica Neue", 0, 14)); // NOI18N
        taAddress.setPlaceholder("TB. Simatupang, Jl. Nangka...");
        scrollAddressTextArea.setViewportView(taAddress);

        errorAddressLabel.setForeground(new Color(220, 53, 69));

        btnSave.setBackground(new Color(61, 169, 252));
        btnSave.setForeground(new Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.setToolTipText("");
        btnSave.setBorderColor(new Color(61, 169, 252));
        btnSave.setColor(new Color(61, 169, 252));
        btnSave.setColorClick(new Color(9, 107, 167));
        btnSave.setColorOver(new Color(12, 126, 195));
        btnSave.setFont(new Font("Helvetica Neue", 1, 13)); // NOI18N

        btnCancel.setBackground(new Color(220, 53, 69));
        btnCancel.setForeground(new Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.setToolTipText("");
        btnCancel.setBorderColor(new Color(220, 53, 69));
        btnCancel.setColor(new Color(220, 53, 69));
        btnCancel.setColorClick(new Color(195, 33, 49));
        btnCancel.setColorOver(new Color(222, 66, 81));
        btnCancel.setFont(new Font("Helvetica Neue", 1, 13)); // NOI18N

        GroupLayout formPanelLayout = new GroupLayout(formPanel);
        formPanel.setLayout(formPanelLayout);
        formPanelLayout.setHorizontalGroup(formPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(formPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(formPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(formPanelLayout.createSequentialGroup()
                        .addComponent(errorBranchNameLabel)
                        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(formPanelLayout.createSequentialGroup()
                        .addGroup(formPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(tfBranchName, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(scrollAddressTextArea, GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                            .addGroup(formPanelLayout.createSequentialGroup()
                                .addGroup(formPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(branchNameLabel)
                                    .addGroup(formPanelLayout.createSequentialGroup()
                                        .addComponent(btnSave, GroupLayout.PREFERRED_SIZE, 110, GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnCancel, GroupLayout.PREFERRED_SIZE, 110, GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(35, 35, 35))
                    .addGroup(formPanelLayout.createSequentialGroup()
                        .addGroup(formPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(errorAddressLabel)
                            .addComponent(addressLabel))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        formPanelLayout.setVerticalGroup(formPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(formPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(branchNameLabel)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfBranchName, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(errorBranchNameLabel)
                .addGap(18, 18, 18)
                .addComponent(addressLabel)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollAddressTextArea, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(errorAddressLabel)
                .addGap(18, 18, 18)
                .addGroup(formPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        branchTable.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));
        branchTable.setModel(new DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "#", "Branch Name", "Address", "Action"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        branchTable.setColumnSelectionAllowed(true);
        branchTable.setSelectionMode(ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        scrollBranchTable.setViewportView(branchTable);
        branchTable.getColumnModel().getSelectionModel().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        branchListTitle.setFont(new Font("Helvetica Neue", 1, 18)); // NOI18N
        branchListTitle.setText("Branch List");

        tfSearch.setPlaceholder("Search");

        searchBtn.setBackground(new Color(95, 108, 123));
        searchBtn.setIcon(new ImageIcon(getClass().getResource("/images/Search.png"))); // NOI18N
        searchBtn.setBorderColor(new Color(95, 108, 123));
        searchBtn.setColor(new Color(95, 108, 123));
        searchBtn.setColorClick(new Color(67, 77, 87));
        searchBtn.setColorOver(new Color(80, 91, 105));

        titleLabel.setFont(new Font("Helvetica Neue", 1, 26)); // NOI18N
        titleLabel.setText("Branch Management");

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleLabel)
                        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(formPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(branchListTitle)
                                .addGap(220, 220, 220)
                                .addComponent(tfSearch, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchBtn, GroupLayout.PREFERRED_SIZE, 36, GroupLayout.PREFERRED_SIZE))
                            .addComponent(scrollBranchTable, GroupLayout.Alignment.TRAILING))
                        .addGap(74, 74, 74))))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(titleLabel)
                .addGap(24, 24, 24)
                .addComponent(formPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(searchBtn, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(branchListTitle)
                        .addComponent(tfSearch, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addComponent(scrollBranchTable, GroupLayout.PREFERRED_SIZE, 247, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getAddressLabel() {
        return addressLabel;
    }

    public void setAddressLabel(JLabel addressLabel) {
        this.addressLabel = addressLabel;
    }

    public JLabel getBranchListTitle() {
        return branchListTitle;
    }

    public void setBranchListTitle(JLabel branchListTitle) {
        this.branchListTitle = branchListTitle;
    }

    public JLabel getBranchNameLabel() {
        return branchNameLabel;
    }

    public void setBranchNameLabel(JLabel branchNameLabel) {
        this.branchNameLabel = branchNameLabel;
    }

    public RoundedButton getBtnSave() {
        return btnSave;
    }

    public void setBtnSave(RoundedButton btnSave) {
        this.btnSave = btnSave;
    }

    public JLabel getErrorAddressLabel() {
        return errorAddressLabel;
    }

    public void setErrorAddressLabel(JLabel errorAddressLabel) {
        this.errorAddressLabel = errorAddressLabel;
    }

    public JLabel getErrorBranchNameLabel() {
        return errorBranchNameLabel;
    }

    public void setErrorBranchNameLabel(JLabel errorBranchNameLabel) {
        this.errorBranchNameLabel = errorBranchNameLabel;
    }

    public RoundedPanel getFormPanel() {
        return formPanel;
    }

    public void setFormPanel(RoundedPanel formPanel) {
        this.formPanel = formPanel;
    }

    public JScrollPane getScrollAddressTextArea() {
        return scrollAddressTextArea;
    }

    public void setScrollAddressTextArea(JScrollPane scrollAddressTextArea) {
        this.scrollAddressTextArea = scrollAddressTextArea;
    }

    public JScrollPane getScrollBranchTable() {
        return scrollBranchTable;
    }

    public void setScrollBranchTable(JScrollPane scrollBranchTable) {
        this.scrollBranchTable = scrollBranchTable;
    }

    public RoundedButton getSearchBtn() {
        return searchBtn;
    }

    public void setSearchBtn(RoundedButton searchBtn) {
        this.searchBtn = searchBtn;
    }

    public RoundedTextArea getTaAddress() {
        return taAddress;
    }

    public void setTaAddress(RoundedTextArea taAddress) {
        this.taAddress = taAddress;
    }

    public Table getBranchTable() {
        return branchTable;
    }

    public void setBranchTable(Table table) {
        this.branchTable = table;
    }

    public RoundedTextField getTfBranchName() {
        return tfBranchName;
    }

    public void setTfBranchName(RoundedTextField tfBranchName) {
        this.tfBranchName = tfBranchName;
    }

    public RoundedTextField getTfSearch() {
        return tfSearch;
    }

    public void setTfSearch(RoundedTextField tfSearch) {
        this.tfSearch = tfSearch;
    }

    public JLabel getTitleLabel() {
        return titleLabel;
    }

    public void setTitleLabel(JLabel titleLabel) {
        this.titleLabel = titleLabel;
    }

    public RoundedButton getBtnCancel() {
        return btnCancel;
    }

    public void setBtnCancel(RoundedButton btnCancel) {
        this.btnCancel = btnCancel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel addressLabel;
    private JLabel branchListTitle;
    private JLabel branchNameLabel;
    private Table branchTable;
    private RoundedButton btnCancel;
    private RoundedButton btnSave;
    private JLabel errorAddressLabel;
    private JLabel errorBranchNameLabel;
    private RoundedPanel formPanel;
    private JScrollPane scrollAddressTextArea;
    private JScrollPane scrollBranchTable;
    private RoundedButton searchBtn;
    private RoundedTextArea taAddress;
    private RoundedTextField tfBranchName;
    private RoundedTextField tfSearch;
    private JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
