/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.xyz.roemahduren.presentation.screen;

import com.xyz.roemahduren.presentation.component.RoundedButton;
import com.xyz.roemahduren.presentation.component.input.RoundedTextField;
import com.xyz.roemahduren.presentation.component.panel.RoundedPanel;
import com.xyz.roemahduren.presentation.component.table.Table;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.GroupLayout;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.LayoutStyle;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class CategoryScreen extends javax.swing.JPanel {

    /**
     * Creates new form CategoryScreen
     */
    public CategoryScreen() {
        initComponents();
        categoryTable.fixTable(categoryScrollPanel);
    }

    public JLabel getBranchListTitle() {
        return branchListTitle;
    }

    public void setBranchListTitle(JLabel branchListTitle) {
        this.branchListTitle = branchListTitle;
    }

    public RoundedButton getBtnCancel() {
        return btnCancel;
    }

    public void setBtnCancel(RoundedButton btnCancel) {
        this.btnCancel = btnCancel;
    }

    public RoundedButton getBtnSave() {
        return btnSave;
    }

    public void setBtnSave(RoundedButton btnSave) {
        this.btnSave = btnSave;
    }

    public JLabel getCategoryNameLabel() {
        return categoryNameLabel;
    }

    public void setCategoryNameLabel(JLabel categoryNameLabel) {
        this.categoryNameLabel = categoryNameLabel;
    }

    public JScrollPane getCategoryScrollPanel() {
        return categoryScrollPanel;
    }

    public void setCategoryScrollPanel(JScrollPane categoryScrollPanel) {
        this.categoryScrollPanel = categoryScrollPanel;
    }

    public Table getCategoryTable() {
        return categoryTable;
    }

    public void setCategoryTable(Table categoryTable) {
        this.categoryTable = categoryTable;
    }

    public JLabel getErrorCategoryNameLabel() {
        return errorCategoryNameLabel;
    }

    public void setErrorCategoryNameLabel(JLabel errorBranchNameLabel) {
        this.errorCategoryNameLabel = errorBranchNameLabel;
    }

    public RoundedPanel getFormPanel() {
        return formPanel;
    }

    public void setFormPanel(RoundedPanel formPanel) {
        this.formPanel = formPanel;
    }

    public RoundedTextField getTfCategoryName() {
        return tfCategoryName;
    }

    public void setTfCategoryName(RoundedTextField tfCategoryName) {
        this.tfCategoryName = tfCategoryName;
    }

    public JLabel getTitleLabel() {
        return titleLabel;
    }

    public void setTitleLabel(JLabel titleLabel) {
        this.titleLabel = titleLabel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new JLabel();
        formPanel = new RoundedPanel();
        categoryNameLabel = new JLabel();
        tfCategoryName = new RoundedTextField();
        errorCategoryNameLabel = new JLabel();
        btnSave = new RoundedButton();
        btnCancel = new RoundedButton();
        categoryScrollPanel = new JScrollPane();
        categoryTable = new Table();
        branchListTitle = new JLabel();

        setBackground(new Color(255, 255, 255));
        setMinimumSize(new Dimension(800, 800));
        setPreferredSize(new Dimension(800, 800));
        setSize(new Dimension(800, 800));

        titleLabel.setFont(new Font("Helvetica Neue", 1, 26)); // NOI18N
        titleLabel.setText("Category Management");

        formPanel.setBackground(new Color(243, 244, 245));
        formPanel.setForeground(new Color(95, 108, 123));
        formPanel.setCornerRadius(8);
        formPanel.setMinimumSize(new Dimension(800, 800));
        formPanel.setPreferredSize(new Dimension(800, 800));

        categoryNameLabel.setForeground(new Color(95, 108, 123));
        categoryNameLabel.setText("Category Name");

        tfCategoryName.setFont(new Font("Helvetica Neue", 0, 14)); // NOI18N
        tfCategoryName.setPlaceholder("Contoh: Rumah Durian");

        errorCategoryNameLabel.setForeground(new Color(220, 53, 69));

        btnSave.setBackground(new Color(61, 169, 252));
        btnSave.setForeground(new Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.setToolTipText("");
        btnSave.setBorderColor(new Color(61, 169, 252));
        btnSave.setColor(new Color(61, 169, 252));
        btnSave.setColorClick(new Color(9, 107, 167));
        btnSave.setColorOver(new Color(12, 126, 195));
        btnSave.setFont(new Font("Helvetica Neue", 1, 13)); // NOI18N

        btnCancel.setBackground(new Color(220, 53, 69));
        btnCancel.setForeground(new Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.setToolTipText("");
        btnCancel.setBorderColor(new Color(220, 53, 69));
        btnCancel.setColor(new Color(220, 53, 69));
        btnCancel.setColorClick(new Color(195, 33, 49));
        btnCancel.setColorOver(new Color(222, 66, 81));
        btnCancel.setFont(new Font("Helvetica Neue", 1, 13)); // NOI18N

        GroupLayout formPanelLayout = new GroupLayout(formPanel);
        formPanel.setLayout(formPanelLayout);
        formPanelLayout.setHorizontalGroup(formPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(formPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(formPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(formPanelLayout.createSequentialGroup()
                        .addComponent(errorCategoryNameLabel)
                        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(formPanelLayout.createSequentialGroup()
                        .addGroup(formPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(tfCategoryName, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(formPanelLayout.createSequentialGroup()
                                .addGroup(formPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(categoryNameLabel)
                                    .addGroup(formPanelLayout.createSequentialGroup()
                                        .addComponent(btnSave, GroupLayout.PREFERRED_SIZE, 110, GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnCancel, GroupLayout.PREFERRED_SIZE, 110, GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(35, 35, 35))))
        );
        formPanelLayout.setVerticalGroup(formPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(formPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(categoryNameLabel)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfCategoryName, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(errorCategoryNameLabel)
                .addGap(18, 18, 18)
                .addGroup(formPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        categoryTable.setModel(new DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Name", "Action"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        categoryTable.setAutoResizeMode(JTable.AUTO_RESIZE_NEXT_COLUMN);
        categoryScrollPanel.setViewportView(categoryTable);

        branchListTitle.setFont(new Font("Helvetica Neue", 1, 18)); // NOI18N
        branchListTitle.setText("Branch List");

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(branchListTitle)
                        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addComponent(categoryScrollPanel, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
                            .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(titleLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(formPanel, GroupLayout.Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 671, Short.MAX_VALUE))
                        .addGap(74, 74, 74))))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(titleLabel)
                .addGap(24, 24, 24)
                .addComponent(formPanel, GroupLayout.PREFERRED_SIZE, 163, GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(branchListTitle)
                .addGap(18, 18, 18)
                .addComponent(categoryScrollPanel, GroupLayout.PREFERRED_SIZE, 366, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel branchListTitle;
    private RoundedButton btnCancel;
    private RoundedButton btnSave;
    private JLabel categoryNameLabel;
    private JScrollPane categoryScrollPanel;
    private Table categoryTable;
    private JLabel errorCategoryNameLabel;
    private RoundedPanel formPanel;
    private RoundedTextField tfCategoryName;
    private JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
