package com.xyz.roemahduren.presentation.screen;

import com.xyz.roemahduren.presentation.component.card.Card;
import com.xyz.roemahduren.presentation.component.panel.RoundedPanel;
import com.xyz.roemahduren.presentation.component.table.Table;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class DashboardScreen extends JPanel {

    /**
     * Creates new form DashboardScreen
     */
    public DashboardScreen() {
        initComponents();  
        table1.fixTable(jScrollPane1);
    }

    public Card getCard1() {
        return card1;
    }

    public Card getCard2() {
        return card2;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public Table getTable1() {
        return table1;
    }

    public JLabel getTitleTable() {
        return titleTable;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeLabel = new JLabel();
        jScrollPane1 = new JScrollPane();
        table1 = new Table();
        card1 = new Card();
        card2 = new Card();
        titleTable = new JLabel();

        setBackground(new Color(255, 255, 254));
        setMinimumSize(new Dimension(800, 600));
        setPreferredSize(new Dimension(800, 600));
        setSize(new Dimension(800, 600));

        welcomeLabel.setFont(new Font("Helvetica Neue", 0, 24)); // NOI18N
        welcomeLabel.setText("Hello Admin!");

        jScrollPane1.setBackground(new Color(243, 244, 245));
        jScrollPane1.setToolTipText("");
        jScrollPane1.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));

        table1.setBackground(new Color(245, 245, 245));
        table1.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));
        table1.setModel(new DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Name", "Product", "Price", "Quantity", "Total Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        table1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(table1);

        card1.setColor1(new Color(221, 83, 83));
        card1.setColor2(new Color(192, 72, 72));

        card2.setColor1(new Color(130, 148, 96));
        card2.setColor2(new Color(108, 122, 80));

        titleTable.setFont(new Font("Helvetica Neue", 0, 22)); // NOI18N
        titleTable.setForeground(new Color(2, 8, 38));
        titleTable.setText("Daftar Transaksi");

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleTable)
                        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(welcomeLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(card1, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(35, 35, 35)
                                .addComponent(card2, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                        .addGap(74, 74, 74))))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(welcomeLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(card1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(titleTable)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                    .addComponent(card2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getWelcomeLabel() {
        return welcomeLabel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Card card1;
    private Card card2;
    private JScrollPane jScrollPane1;
    private Table table1;
    private JLabel titleTable;
    private JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
