/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.xyz.roemahduren.presentation.screen;

import com.xyz.roemahduren.presentation.component.ImagePanel;
import com.xyz.roemahduren.presentation.component.LabelLink;
import com.xyz.roemahduren.presentation.component.RoundedButton;
import com.xyz.roemahduren.presentation.component.RoundedPasswordField;
import com.xyz.roemahduren.presentation.component.RoundedTextField;
import com.xyz.roemahduren.util.SwingUtil;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.*;
import javax.swing.border.BevelBorder;
import javax.swing.border.SoftBevelBorder;
import javax.swing.event.AncestorEvent;
import javax.swing.event.AncestorListener;

/**
 *
 * @author user
 */
public class LoginScreen extends javax.swing.JFrame {

    /**
     * Creates new form LoginScreen
     */
    public LoginScreen() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        SwingUtil.centerWindow(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfEmail = new RoundedTextField();
        emailLabel = new JLabel();
        errorEmailLabel = new JLabel();
        passwordLabel = new JLabel();
        errorPasswordLabel = new JLabel();
        titleLabel = new JLabel();
        registerLabelDescription = new JLabel();
        signInBtn = new RoundedButton();
        forgotPasswordLabel = new LabelLink();
        registerLabelLink = new LabelLink();
        tfPassword = new RoundedPasswordField();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new Dimension(480, 500));
        setMinimumSize(new Dimension(480, 500));
        setSize(new Dimension(480, 500));

        tfEmail.setPlaceholder("johndoe@mail.com");

        emailLabel.setForeground(new Color(49, 53, 59));
        emailLabel.setLabelFor(tfEmail);
        emailLabel.setText("Email");

        errorEmailLabel.setForeground(new Color(220, 53, 69));

        passwordLabel.setForeground(new Color(49, 53, 59));
        passwordLabel.setLabelFor(tfPassword);
        passwordLabel.setText("Password");

        errorPasswordLabel.setForeground(new Color(220, 53, 69));

        titleLabel.setFont(new Font("Helvetica Neue", 0, 18)); // NOI18N
        titleLabel.setForeground(new Color(49, 53, 59));
        titleLabel.setText("Login to your account");

        registerLabelDescription.setForeground(new Color(49, 53, 59));
        registerLabelDescription.setText("Don't have an account?");

        signInBtn.setBorder(null);
        signInBtn.setForeground(new Color(255, 255, 255));
        signInBtn.setText("Sign In");
        signInBtn.setFont(new Font("Helvetica Neue", 1, 14)); // NOI18N

        forgotPasswordLabel.setForeground(new Color(49, 53, 59));
        forgotPasswordLabel.setText("Forgot Password?");

        registerLabelLink.setForeground(new Color(49, 53, 59));
        registerLabelLink.setText("Register");

        tfPassword.setPlaceholder("p@ssword");

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(titleLabel)
                    .addComponent(passwordLabel)
                    .addComponent(forgotPasswordLabel, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(registerLabelDescription)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(registerLabelLink, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfEmail, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(signInBtn, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(errorPasswordLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(errorEmailLabel, GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                    .addComponent(tfPassword, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addComponent(emailLabel)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfEmail, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorEmailLabel)
                .addGap(16, 16, 16)
                .addComponent(passwordLabel)
                .addGap(4, 4, 4)
                .addComponent(tfPassword, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorPasswordLabel)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(signInBtn, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(registerLabelDescription)
                            .addComponent(registerLabelLink, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(111, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(forgotPasswordLabel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getEmailLabel() {
        return emailLabel;
    }

    public void setEmailLabel(JLabel emailLabel) {
        this.emailLabel = emailLabel;
    }

    public JLabel getErrorEmailLabel() {
        return errorEmailLabel;
    }

    public void setErrorEmailLabel(JLabel errorEmailLabel) {
        this.errorEmailLabel = errorEmailLabel;
    }

    public JLabel getErrorPasswordLabel() {
        return errorPasswordLabel;
    }

    public void setErrorPasswordLabel(JLabel errorPasswordLabel) {
        this.errorPasswordLabel = errorPasswordLabel;
    }

    public LabelLink getForgotPasswordLabel() {
        return forgotPasswordLabel;
    }

    public void setForgotPasswordLabel(LabelLink forgotPasswordLabel) {
        this.forgotPasswordLabel = forgotPasswordLabel;
    }

    public JLabel getPasswordLabel() {
        return passwordLabel;
    }

    public void setPasswordLabel(JLabel passwordLabel) {
        this.passwordLabel = passwordLabel;
    }

    public JLabel getRegisterLabelDescription() {
        return registerLabelDescription;
    }

    public void setRegisterLabelDescription(JLabel registerLabelDescription) {
        this.registerLabelDescription = registerLabelDescription;
    }

    public LabelLink getRegisterLabelLink() {
        return registerLabelLink;
    }

    public void setRegisterLabelLink(LabelLink registerLabelLink) {
        this.registerLabelLink = registerLabelLink;
    }

    public RoundedButton getSignInBtn() {
        return signInBtn;
    }

    public void setSignInBtn(RoundedButton signInBtn) {
        this.signInBtn = signInBtn;
    }

    public RoundedTextField getTfEmail() {
        return tfEmail;
    }

    public void setTfEmail(RoundedTextField tfEmail) {
        this.tfEmail = tfEmail;
    }

    public RoundedPasswordField getTfPassword() {
        return tfPassword;
    }

    public void RoundedPasswordField(RoundedPasswordField tfPassword) {
        this.tfPassword = tfPassword;
    }

    public JLabel getTitleLabel() {
        return titleLabel;
    }

    public void setTitleLabel(JLabel titleLabel) {
        this.titleLabel = titleLabel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel emailLabel;
    private JLabel errorEmailLabel;
    private JLabel errorPasswordLabel;
    private LabelLink forgotPasswordLabel;
    private JLabel passwordLabel;
    private JLabel registerLabelDescription;
    private LabelLink registerLabelLink;
    private RoundedButton signInBtn;
    private RoundedTextField tfEmail;
    private RoundedPasswordField tfPassword;
    private JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
