/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.xyz.roemahduren.presentation.screen;

import com.xyz.roemahduren.presentation.component.LabelLink;
import com.xyz.roemahduren.presentation.component.RoundedButton;
import com.xyz.roemahduren.presentation.component.input.RoundedPasswordFieldPanel;
import com.xyz.roemahduren.presentation.component.input.RoundedTextFieldPanel;
import com.xyz.roemahduren.util.SwingUtil;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author user
 */
public class LoginScreen extends javax.swing.JFrame {

    /**
     * Creates new form LoginScreen
     */
    public LoginScreen() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        SwingUtil.centerWindow(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new JLabel();
        registerLabelDescription = new JLabel();
        signInBtn = new RoundedButton();
        forgotPasswordLabel = new LabelLink();
        registerLabelLink = new LabelLink();
        passwordTf = new RoundedPasswordFieldPanel();
        emailTf = new RoundedTextFieldPanel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("Masuk Roemah Duren");
        setMaximumSize(new Dimension(480, 500));
        setMinimumSize(new Dimension(480, 500));
        setSize(new Dimension(480, 500));

        titleLabel.setFont(new Font("Helvetica Neue", 0, 18)); // NOI18N
        titleLabel.setForeground(new Color(49, 53, 59));
        titleLabel.setText("Masuk Ke Akun Anda");

        registerLabelDescription.setForeground(new Color(49, 53, 59));
        registerLabelDescription.setText("Belum punya akun?");

        signInBtn.setBackground(new Color(221, 83, 83));
        signInBtn.setBorder(null);
        signInBtn.setForeground(new Color(255, 255, 255));
        signInBtn.setText("Masuk");
        signInBtn.setBorderColor(new Color(221, 83, 83));
        signInBtn.setColor(new Color(221, 83, 83));
        signInBtn.setColorClick(new Color(192, 72, 72));
        signInBtn.setColorOver(new Color(204, 77, 77));
        signInBtn.setFont(new Font("Helvetica Neue", 1, 14)); // NOI18N

        forgotPasswordLabel.setForeground(new Color(49, 53, 59));
        forgotPasswordLabel.setText("Lupa Kata Sandi?");

        registerLabelLink.setForeground(new Color(49, 53, 59));
        registerLabelLink.setText("Daftar");

        passwordTf.setBackground(new Color(255, 255, 254));
        passwordTf.setErrorMessage("");
        passwordTf.setLabelText("Kata Sandi");
        passwordTf.setValue("");

        emailTf.setBackground(new Color(255, 255, 254));
        emailTf.setErrorMessage("");
        emailTf.setLabelText("Email");

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(titleLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(registerLabelDescription)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(registerLabelLink, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(forgotPasswordLabel, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(signInBtn, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 305, GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(passwordTf, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(emailTf, GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE))))
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addComponent(emailTf, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordTf, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(signInBtn, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(registerLabelDescription)
                            .addComponent(registerLabelLink, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                    .addComponent(forgotPasswordLabel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public RoundedTextFieldPanel getEmailTf() {
        return emailTf;
    }

    public RoundedPasswordFieldPanel getPasswordTf() {
        return passwordTf;
    }

    public LabelLink getForgotPasswordLabel() {
        return forgotPasswordLabel;
    }

    public void setForgotPasswordLabel(LabelLink forgotPasswordLabel) {
        this.forgotPasswordLabel = forgotPasswordLabel;
    }


    public JLabel getRegisterLabelDescription() {
        return registerLabelDescription;
    }

    public void setRegisterLabelDescription(JLabel registerLabelDescription) {
        this.registerLabelDescription = registerLabelDescription;
    }

    public LabelLink getRegisterLabelLink() {
        return registerLabelLink;
    }

    public void setRegisterLabelLink(LabelLink registerLabelLink) {
        this.registerLabelLink = registerLabelLink;
    }

    public RoundedButton getSignInBtn() {
        return signInBtn;
    }

    public void setSignInBtn(RoundedButton signInBtn) {
        this.signInBtn = signInBtn;
    }

    public JLabel getTitleLabel() {
        return titleLabel;
    }

    public void setTitleLabel(JLabel titleLabel) {
        this.titleLabel = titleLabel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RoundedTextFieldPanel emailTf;
    private LabelLink forgotPasswordLabel;
    private RoundedPasswordFieldPanel passwordTf;
    private JLabel registerLabelDescription;
    private LabelLink registerLabelLink;
    private RoundedButton signInBtn;
    private JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
