/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.xyz.roemahduren.presentation.screen;

import com.xyz.roemahduren.presentation.component.menu.MenuItem;
import com.xyz.roemahduren.presentation.component.menu.SideMenu;
import com.xyz.roemahduren.presentation.component.panel.RoundedPanel;
import com.xyz.roemahduren.presentation.component.scroll.ScrollBar;

import java.awt.*;
import java.util.List;
import javax.swing.*;

/**
 *
 * @author user
 */
public class MainScreen extends JFrame {

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();

        contentMenuScroll.setBorder(null);
        contentMenuScroll.setVerticalScrollBar(new ScrollBar());
        contentMenuScroll.setHorizontalScrollBar(new ScrollBar());
        contentMenuScroll.getVerticalScrollBar().setBackground(Color.WHITE);
        contentMenuScroll.getViewport().setBackground(Color.WHITE);
        JPanel p = new JPanel();
        p.setBackground(Color.WHITE);
        contentMenuScroll.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sideMenuPanel = new SideMenu();
        contentMenuScroll = new JScrollPane();
        dashboardScreen = new DashboardScreen();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new Dimension(1024, 720));
        setSize(new Dimension(1024, 720));

        dashboardScreen.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));
        contentMenuScroll.setViewportView(dashboardScreen);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sideMenuPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(contentMenuScroll))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(sideMenuPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contentMenuScroll, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JScrollPane getContentMenuScroll() {
        return contentMenuScroll;
    }

    public void setContentMenuScroll(JScrollPane contentMenuScroll) {
        this.contentMenuScroll = contentMenuScroll;
    }

    public DashboardScreen getDashboardScreen() {
        return dashboardScreen;
    }

    public void setDashboardScreen(DashboardScreen dashboardScreen) {
        this.dashboardScreen = dashboardScreen;
    }

    public SideMenu getSideMenuPanel() {
        return sideMenuPanel;
    }

    public void setSideMenuPanel(SideMenu sideMenuPanel) {
        this.sideMenuPanel = sideMenuPanel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JScrollPane contentMenuScroll;
    private DashboardScreen dashboardScreen;
    private SideMenu sideMenuPanel;
    // End of variables declaration//GEN-END:variables
}
