/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.xyz.roemahduren.presentation.screen;

import com.xyz.roemahduren.presentation.component.menu.SideMenu;
import com.xyz.roemahduren.presentation.component.scroll.ScrollBar;
import com.xyz.roemahduren.util.SwingUtil;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author user
 */
public class MainScreen extends JFrame {

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
        fixScrollPane(contentMenuScroll);
        fixScrollPane(sideMenuScroll);
        SwingUtil.centerWindow(this);
    }

    private void fixScrollPane(JScrollPane jScrollPane) {
        jScrollPane.setBorder(null);
        jScrollPane.setVerticalScrollBar(new ScrollBar());
        jScrollPane.setHorizontalScrollBar(new ScrollBar());
        jScrollPane.getVerticalScrollBar().setBackground(Color.WHITE);
        jScrollPane.getViewport().setBackground(Color.WHITE);
        JPanel p = new JPanel();
        p.setBackground(Color.WHITE);
        jScrollPane.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sideMenuScroll = new JScrollPane();
        sideMenuPanel = new SideMenu();
        contentMenuScroll = new JScrollPane();
        dashboardScreen = new DashboardScreen();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new Dimension(1280, 800));
        setPreferredSize(new Dimension(1280, 800));
        setSize(new Dimension(1280, 600));

        sideMenuPanel.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
        sideMenuPanel.setPreferredSize(new Dimension(300, 800));
        sideMenuScroll.setViewportView(sideMenuPanel);

        dashboardScreen.setMinimumSize(new Dimension(0, 0));
        dashboardScreen.setName(""); // NOI18N
        contentMenuScroll.setViewportView(dashboardScreen);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sideMenuScroll, GroupLayout.PREFERRED_SIZE, 315, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(contentMenuScroll, GroupLayout.DEFAULT_SIZE, 965, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(contentMenuScroll)
            .addComponent(sideMenuScroll, GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JScrollPane getContentMenuScroll() {
        return contentMenuScroll;
    }

    public void setContentMenuScroll(JScrollPane contentMenuScroll) {
        this.contentMenuScroll = contentMenuScroll;
    }

    public DashboardScreen getDashboardScreen() {
        return dashboardScreen;
    }

    public void setDashboardScreen(DashboardScreen dashboardScreen) {
        this.dashboardScreen = dashboardScreen;
    }

    public SideMenu getSideMenuPanel() {
        return sideMenuPanel;
    }

    public void setSideMenuPanel(SideMenu sideMenuPanel) {
        this.sideMenuPanel = sideMenuPanel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JScrollPane contentMenuScroll;
    private DashboardScreen dashboardScreen;
    private SideMenu sideMenuPanel;
    private JScrollPane sideMenuScroll;
    // End of variables declaration//GEN-END:variables
}
