/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.xyz.roemahduren.presentation.screen;

import com.xyz.roemahduren.presentation.component.RoundedButton;
import com.xyz.roemahduren.presentation.component.input.RoundedSpinnerPanel;
import com.xyz.roemahduren.presentation.component.input.RoundedTextFieldPanel;
import com.xyz.roemahduren.presentation.component.panel.RoundedPanel;
import com.xyz.roemahduren.presentation.component.table.Table;
import com.xyz.roemahduren.util.SwingUtil;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class OrderScreen extends javax.swing.JPanel {

    /**
     * Creates new form OrderScreen
     */
    public OrderScreen() {
        initComponents();
        SwingUtil.fixScroll(scrollTable);
        SwingUtil.fixScroll(scrollTransactionDetail);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleScreen = new JLabel();
        titleTableProduct = new JLabel();
        scrollTable = new JScrollPane();
        productTable = new Table();
        searchProductTextField = new RoundedTextFieldPanel();
        searchBtn = new RoundedButton();
        titleTableProduct1 = new JLabel();
        productListPanel = new RoundedPanel();
        addProductBtn = new RoundedButton();
        productNameTf = new RoundedTextFieldPanel();
        productCategoryTf = new RoundedTextFieldPanel();
        cancelProductBtn = new RoundedButton();
        quantitySpinner = new RoundedSpinnerPanel();
        scrollTransactionDetail = new JScrollPane();
        detailTransactionTable = new Table();
        totalTransactionPanel = new RoundedPanel();
        clearCartBtn = new RoundedButton();
        checkoutBtn = new RoundedButton();
        titleTotalTransaction = new JLabel();
        titleTotalPrice = new JLabel();
        customerNameTf = new RoundedTextFieldPanel();

        setBackground(new Color(255, 255, 254));
        setMinimumSize(new Dimension(800, 1300));
        setPreferredSize(new Dimension(800, 1300));
        setSize(new Dimension(800, 1300));

        titleScreen.setFont(new Font("Helvetica Neue", 1, 24)); // NOI18N
        titleScreen.setForeground(new Color(2, 8, 38));
        titleScreen.setText("Manajemen Pesanan");

        titleTableProduct.setFont(new Font("Helvetica Neue", 0, 22)); // NOI18N
        titleTableProduct.setForeground(new Color(2, 8, 38));
        titleTableProduct.setText("Daftar Produk");

        productTable.setModel(new DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollTable.setViewportView(productTable);

        searchProductTextField.setBackground(new Color(255, 255, 254));
        searchProductTextField.setLabelErrorText("");
        searchProductTextField.setLabelText("Cari");

        searchBtn.setText("Cari");
        searchBtn.setFont(new Font("Helvetica Neue", 1, 13)); // NOI18N

        titleTableProduct1.setFont(new Font("Helvetica Neue", 0, 22)); // NOI18N
        titleTableProduct1.setForeground(new Color(2, 8, 38));
        titleTableProduct1.setText("Detail Transaksi");

        productListPanel.setBackground(new Color(245, 245, 245));
        productListPanel.setCornerRadius(8);

        addProductBtn.setText("Tambah");
        addProductBtn.setFont(new Font("Helvetica Neue", 1, 13)); // NOI18N

        productNameTf.setBackground(new Color(245, 245, 245));
        productNameTf.setLabelErrorText("");
        productNameTf.setLabelText("Nama Produk");

        productCategoryTf.setBackground(new Color(245, 245, 245));
        productCategoryTf.setLabelErrorText("");
        productCategoryTf.setLabelText("Kategori");

        cancelProductBtn.setBackground(new Color(221, 83, 83));
        cancelProductBtn.setText("Batalkan");
        cancelProductBtn.setBorderColor(new Color(221, 83, 83));
        cancelProductBtn.setColor(new Color(221, 83, 83));
        cancelProductBtn.setColorClick(new Color(204, 77, 77));
        cancelProductBtn.setColorOver(new Color(204, 77, 77));
        cancelProductBtn.setFont(new Font("Helvetica Neue", 1, 13)); // NOI18N

        quantitySpinner.setBackground(new Color(245, 245, 245));
        quantitySpinner.setLabelErrorText("");
        quantitySpinner.setLabelText("Kuantitas");

        GroupLayout productListPanelLayout = new GroupLayout(productListPanel);
        productListPanel.setLayout(productListPanelLayout);
        productListPanelLayout.setHorizontalGroup(productListPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(productListPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(productListPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(productListPanelLayout.createSequentialGroup()
                        .addComponent(productNameTf, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(productCategoryTf, GroupLayout.PREFERRED_SIZE, 239, GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(productListPanelLayout.createSequentialGroup()
                        .addComponent(addProductBtn, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cancelProductBtn, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(167, 167, 167)))
                .addComponent(quantitySpinner, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        productListPanelLayout.setVerticalGroup(productListPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(productListPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(productListPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(quantitySpinner, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addGroup(productListPanelLayout.createSequentialGroup()
                        .addGroup(productListPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(productNameTf, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(productCategoryTf, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(productListPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(addProductBtn, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelProductBtn, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        detailTransactionTable.setModel(new DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollTransactionDetail.setViewportView(detailTransactionTable);

        totalTransactionPanel.setBackground(new Color(245, 245, 245));
        totalTransactionPanel.setCornerRadius(8);

        clearCartBtn.setBackground(new Color(221, 83, 83));
        clearCartBtn.setIcon(new ImageIcon(getClass().getResource("/images/Shopping Cart.png"))); // NOI18N
        clearCartBtn.setText("Hapus Semua Keranjang");
        clearCartBtn.setBorderColor(new Color(221, 83, 83));
        clearCartBtn.setColor(new Color(221, 83, 83));
        clearCartBtn.setColorClick(new Color(204, 77, 77));
        clearCartBtn.setColorOver(new Color(204, 77, 77));
        clearCartBtn.setFont(new Font("Helvetica Neue", 1, 13)); // NOI18N

        checkoutBtn.setText("Pesan");
        checkoutBtn.setFont(new Font("Helvetica Neue", 1, 13)); // NOI18N

        titleTotalTransaction.setFont(new Font("Helvetica Neue", 0, 20)); // NOI18N
        titleTotalTransaction.setForeground(new Color(2, 8, 38));
        titleTotalTransaction.setText("Total Bayar");

        titleTotalPrice.setFont(new Font("Helvetica Neue", 1, 18)); // NOI18N
        titleTotalPrice.setForeground(new Color(2, 8, 38));
        titleTotalPrice.setText("Rp 0");

        customerNameTf.setBackground(new Color(245, 245, 245));
        customerNameTf.setLabelErrorText("");
        customerNameTf.setLabelText("Nama Pelanggan");

        GroupLayout totalTransactionPanelLayout = new GroupLayout(totalTransactionPanel);
        totalTransactionPanel.setLayout(totalTransactionPanelLayout);
        totalTransactionPanelLayout.setHorizontalGroup(totalTransactionPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(totalTransactionPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(totalTransactionPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(customerNameTf, GroupLayout.PREFERRED_SIZE, 313, GroupLayout.PREFERRED_SIZE)
                    .addGroup(totalTransactionPanelLayout.createSequentialGroup()
                        .addComponent(checkoutBtn, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(clearCartBtn, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addComponent(titleTotalPrice)
                    .addComponent(titleTotalTransaction))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        totalTransactionPanelLayout.setVerticalGroup(totalTransactionPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, totalTransactionPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(customerNameTf, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(titleTotalTransaction)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(titleTotalPrice)
                .addGap(24, 24, 24)
                .addGroup(totalTransactionPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(checkoutBtn, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearCartBtn, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleTableProduct1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addComponent(totalTransactionPanel, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(scrollTransactionDetail, GroupLayout.Alignment.LEADING)
                            .addComponent(productListPanel, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(scrollTable, GroupLayout.Alignment.LEADING)
                            .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(titleScreen)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(titleTableProduct)
                                .addGap(176, 176, 176)
                                .addComponent(searchProductTextField, GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(searchBtn, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                        .addGap(74, 74, 74))))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(titleScreen)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(searchProductTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleTableProduct)
                        .addGap(11, 11, 11))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchBtn, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollTable, GroupLayout.PREFERRED_SIZE, 307, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(productListPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(titleTableProduct1)
                .addGap(18, 18, 18)
                .addComponent(scrollTransactionDetail, GroupLayout.PREFERRED_SIZE, 237, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(totalTransactionPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RoundedButton addProductBtn;
    private RoundedButton cancelProductBtn;
    private RoundedButton checkoutBtn;
    private RoundedButton clearCartBtn;
    private RoundedTextFieldPanel customerNameTf;
    private Table detailTransactionTable;
    private RoundedTextFieldPanel productCategoryTf;
    private RoundedPanel productListPanel;
    private RoundedTextFieldPanel productNameTf;
    private Table productTable;
    private RoundedSpinnerPanel quantitySpinner;
    private JScrollPane scrollTable;
    private JScrollPane scrollTransactionDetail;
    private RoundedButton searchBtn;
    private RoundedTextFieldPanel searchProductTextField;
    private JLabel titleScreen;
    private JLabel titleTableProduct;
    private JLabel titleTableProduct1;
    private JLabel titleTotalPrice;
    private JLabel titleTotalTransaction;
    private RoundedPanel totalTransactionPanel;
    // End of variables declaration//GEN-END:variables
}
