package com.xyz.roemahduren.presentation.screen;

import com.xyz.roemahduren.presentation.component.LabelLink;
import com.xyz.roemahduren.presentation.component.RoundedButton;
import com.xyz.roemahduren.presentation.component.input.RoundedPasswordField;
import com.xyz.roemahduren.presentation.component.input.RoundedPasswordFieldPanel;
import com.xyz.roemahduren.presentation.component.input.RoundedTextField;
import com.xyz.roemahduren.presentation.component.input.RoundedTextFieldPanel;
import com.xyz.roemahduren.util.SwingUtil;

import javax.swing.*;
import java.awt.*;

/**
 * @author user
 */
public class RegisterScreen extends JFrame {

    /**
     * Creates new form RegisterScreen
     */
    public RegisterScreen() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        SwingUtil.centerWindow(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new JLabel();
        loginLabelText = new JLabel();
        registerBtn = new RoundedButton();
        loginLabelLink = new LabelLink();
        emailTf = new RoundedTextFieldPanel();
        passwordTf = new RoundedPasswordFieldPanel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("Daftar Roemah Duren");
        setMaximumSize(new Dimension(480, 500));
        setMinimumSize(new Dimension(480, 500));
        setSize(new Dimension(480, 500));

        titleLabel.setFont(new Font("Helvetica Neue", 0, 18)); // NOI18N
        titleLabel.setForeground(new Color(49, 53, 59));
        titleLabel.setText("Buat Akun Baru");

        loginLabelText.setForeground(new Color(49, 53, 59));
        loginLabelText.setText("Sudah punya akun?");

        registerBtn.setBackground(new Color(221, 83, 83));
        registerBtn.setBorder(null);
        registerBtn.setForeground(new Color(255, 255, 255));
        registerBtn.setText("Daftar");
        registerBtn.setBorderColor(new Color(221, 83, 83));
        registerBtn.setColor(new Color(221, 83, 83));
        registerBtn.setColorClick(new Color(192, 72, 72));
        registerBtn.setColorOver(new Color(204, 77, 77));
        registerBtn.setFont(new Font("Helvetica Neue", 1, 14)); // NOI18N

        loginLabelLink.setForeground(new Color(49, 53, 59));
        loginLabelLink.setText("Masuk");

        emailTf.setBackground(new Color(255, 255, 254));
        emailTf.setErrorMessage("");
        emailTf.setLabelText("Email");

        passwordTf.setBackground(new Color(255, 255, 254));
        passwordTf.setLabelErrorText("");
        passwordTf.setLabelText("Kata Sandi");
        passwordTf.setValue("");

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                        .addComponent(passwordTf, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(emailTf, GroupLayout.PREFERRED_SIZE, 305, GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(titleLabel)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(loginLabelText)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(loginLabelLink, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addComponent(registerBtn, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 305, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addComponent(emailTf, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordTf, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(registerBtn, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(loginLabelText)
                    .addComponent(loginLabelLink, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(136, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public LabelLink getLoginLabelLink() {
        return loginLabelLink;
    }

    public void setLoginLabelLink(LabelLink loginLabelLink) {
        this.loginLabelLink = loginLabelLink;
    }

    public JLabel getLoginLabelText() {
        return loginLabelText;
    }

    public void setLoginLabelText(JLabel loginLabelText) {
        this.loginLabelText = loginLabelText;
    }

    public RoundedButton getRegisterBtn() {
        return registerBtn;
    }

    public void setRegisterBtn(RoundedButton registerBtn) {
        this.registerBtn = registerBtn;
    }
    
    public JLabel getTitleLabel() {
        return titleLabel;
    }

    public void setTitleLabel(JLabel titleLabel) {
        this.titleLabel = titleLabel;
    }

    public RoundedTextFieldPanel getEmailTf() {
        return emailTf;
    }

    public RoundedPasswordFieldPanel getPasswordTf() {
        return passwordTf;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RoundedTextFieldPanel emailTf;
    private LabelLink loginLabelLink;
    private JLabel loginLabelText;
    private RoundedPasswordFieldPanel passwordTf;
    private RoundedButton registerBtn;
    private JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
