/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.xyz.roemahduren.presentation.screen;

import com.xyz.roemahduren.presentation.component.RoundedButton;
import com.xyz.roemahduren.presentation.component.input.RoundedPasswordFieldPanel;
import com.xyz.roemahduren.presentation.component.input.RoundedTextAreaPanel;
import com.xyz.roemahduren.presentation.component.input.RoundedTextFieldPanel;
import com.xyz.roemahduren.presentation.component.panel.RoundedPanel;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Point;
import javax.swing.GroupLayout;
import javax.swing.JLabel;
import javax.swing.LayoutStyle;

/**
 *
 * @author user
 */
public class SettingScreen extends javax.swing.JPanel {

    /**
     * Creates new form ProfileSettingScreen
     */
    public SettingScreen() {
        initComponents();
        emailTextField.getTextField().setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleScreen = new JLabel();
        userFormPanel = new RoundedPanel();
        saveBtn = new RoundedButton();
        passwordField = new RoundedPasswordFieldPanel();
        emailTextField = new RoundedTextFieldPanel();
        confirmPasswordField = new RoundedPasswordFieldPanel();
        titleScreen1 = new JLabel();

        setBackground(new Color(255, 255, 254));
        setLocation(new Point(800, 600));
        setMinimumSize(new Dimension(800, 600));
        setPreferredSize(new Dimension(800, 600));
        setSize(new Dimension(800, 600));

        titleScreen.setFont(new Font("Helvetica Neue", 1, 24)); // NOI18N
        titleScreen.setForeground(new Color(2, 8, 38));
        titleScreen.setText("Pengaturan");

        userFormPanel.setBackground(new Color(245, 245, 245));
        userFormPanel.setCornerRadius(8);

        saveBtn.setText("Simpan Password");
        saveBtn.setFont(new Font("Helvetica Neue", 1, 13)); // NOI18N

        passwordField.setBackground(new Color(245, 245, 245));
        passwordField.setLabelErrorText("");
        passwordField.setLabelText("Kata Sandi Baru");
        passwordField.setValue("");

        emailTextField.setBackground(new Color(245, 245, 245));
        emailTextField.setEnabled(false);
        emailTextField.setErrorMessage("");
        emailTextField.setLabelText("Email");

        confirmPasswordField.setBackground(new Color(245, 245, 245));
        confirmPasswordField.setLabelErrorText("");
        confirmPasswordField.setLabelText("Konfirmasi Kata Sandi Baru");
        confirmPasswordField.setValue("");

        GroupLayout userFormPanelLayout = new GroupLayout(userFormPanel);
        userFormPanel.setLayout(userFormPanelLayout);
        userFormPanelLayout.setHorizontalGroup(userFormPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(userFormPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(userFormPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(saveBtn, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailTextField, GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                    .addComponent(passwordField, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(confirmPasswordField, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        userFormPanelLayout.setVerticalGroup(userFormPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(userFormPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(emailTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(confirmPasswordField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(saveBtn, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        titleScreen1.setFont(new Font("Helvetica Neue", 0, 20)); // NOI18N
        titleScreen1.setForeground(new Color(2, 8, 38));
        titleScreen1.setText("Ubah Kata Sandi");

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(userFormPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titleScreen)
                    .addComponent(titleScreen1))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(titleScreen)
                .addGap(26, 26, 26)
                .addComponent(titleScreen1)
                .addGap(18, 18, 18)
                .addComponent(userFormPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public RoundedPasswordFieldPanel getConfirmPasswordField() {
        return confirmPasswordField;
    }

    public RoundedTextFieldPanel getEmailTextField() {
        return emailTextField;
    }

    public RoundedPasswordFieldPanel getPasswordField() {
        return passwordField;
    }

    public RoundedButton getSaveBtn() {
        return saveBtn;
    }

    public JLabel getTitleScreen() {
        return titleScreen;
    }

    public RoundedPanel getUserFormPanel() {
        return userFormPanel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RoundedPasswordFieldPanel confirmPasswordField;
    private RoundedTextFieldPanel emailTextField;
    private RoundedPasswordFieldPanel passwordField;
    private RoundedButton saveBtn;
    private JLabel titleScreen;
    private JLabel titleScreen1;
    private RoundedPanel userFormPanel;
    // End of variables declaration//GEN-END:variables
}
