/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.xyz.roemahduren.presentation.screen;

import com.xyz.roemahduren.presentation.component.RoundedButton;
import com.xyz.roemahduren.presentation.component.input.RoundedPasswordFieldPanel;
import com.xyz.roemahduren.presentation.component.input.RoundedTextFieldPanel;

import javax.swing.*;

/**
 *
 * @author user
 */
public class SettingScreen2 extends javax.swing.JPanel {

    /**
     * Creates new form SettingScreen2
     */
    public SettingScreen2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        confirmPasswordField = new com.xyz.roemahduren.presentation.component.input.RoundedPasswordFieldPanel();
        saveBtn = new com.xyz.roemahduren.presentation.component.RoundedButton();
        passwordField = new com.xyz.roemahduren.presentation.component.input.RoundedPasswordFieldPanel();
        emailTextField = new com.xyz.roemahduren.presentation.component.input.RoundedTextFieldPanel();
        titleScreen1 = new javax.swing.JLabel();
        titleScreen = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 254));

        confirmPasswordField.setBackground(new java.awt.Color(255, 255, 254));
        confirmPasswordField.setLabelErrorText("");
        confirmPasswordField.setLabelText("Konfirmasi Kata Sandi Baru");
        confirmPasswordField.setValue("");

        saveBtn.setText("Simpan Password");
        saveBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N

        passwordField.setBackground(new java.awt.Color(255, 255, 254));
        passwordField.setLabelErrorText("");
        passwordField.setLabelText("Kata Sandi Baru");
        passwordField.setValue("");

        emailTextField.setBackground(new java.awt.Color(255, 255, 254));
        emailTextField.setEnabled(false);
        emailTextField.setErrorMessage("");
        emailTextField.setLabelText("Email");

        titleScreen1.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        titleScreen1.setForeground(new java.awt.Color(2, 8, 38));
        titleScreen1.setText("Ubah Kata Sandi");

        titleScreen.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        titleScreen.setForeground(new java.awt.Color(2, 8, 38));
        titleScreen.setText("Pengaturan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(confirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titleScreen)
                            .addComponent(titleScreen1)
                            .addComponent(emailTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                            .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(titleScreen)
                .addGap(26, 26, 26)
                .addComponent(titleScreen1)
                .addGap(18, 18, 18)
                .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(confirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public RoundedPasswordFieldPanel getConfirmPasswordField() {
        return confirmPasswordField;
    }

    public RoundedTextFieldPanel getEmailTextField() {
        return emailTextField;
    }

    public RoundedPasswordFieldPanel getPasswordField() {
        return passwordField;
    }

    public RoundedButton getSaveBtn() {
        return saveBtn;
    }

    public JLabel getTitleScreen() {
        return titleScreen;
    }

    public JLabel getTitleScreen1() {
        return titleScreen1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.xyz.roemahduren.presentation.component.input.RoundedPasswordFieldPanel confirmPasswordField;
    private com.xyz.roemahduren.presentation.component.input.RoundedTextFieldPanel emailTextField;
    private com.xyz.roemahduren.presentation.component.input.RoundedPasswordFieldPanel passwordField;
    private com.xyz.roemahduren.presentation.component.RoundedButton saveBtn;
    private javax.swing.JLabel titleScreen;
    private javax.swing.JLabel titleScreen1;
    // End of variables declaration//GEN-END:variables
}
