/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.xyz.roemahduren.presentation.screen;

import com.xyz.roemahduren.presentation.component.RoundedButton;
import com.xyz.roemahduren.presentation.component.input.RoundedPasswordFieldPanel;
import com.xyz.roemahduren.presentation.component.input.RoundedTextFieldPanel;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Point;
import javax.swing.GroupLayout;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;

/**
 *
 * @author user
 */
public class SettingScreen extends javax.swing.JPanel {

    /**
     * Creates new form ProfileSettingScreen
     */
    public SettingScreen() {
        initComponents();
        emailTextField.getTextField().setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new JTextField();
        titleScreen = new JLabel();
        titleScreen1 = new JLabel();
        emailTextField = new RoundedTextFieldPanel();
        passwordField = new RoundedPasswordFieldPanel();
        confirmPasswordField = new RoundedPasswordFieldPanel();
        saveBtn = new RoundedButton();

        jTextField1.setText("jTextField1");

        setBackground(new Color(255, 255, 254));
        setLocation(new Point(800, 600));
        setMinimumSize(new Dimension(800, 600));
        setPreferredSize(new Dimension(800, 600));
        setSize(new Dimension(800, 600));

        titleScreen.setFont(new Font("Helvetica Neue", 1, 24)); // NOI18N
        titleScreen.setForeground(new Color(2, 8, 38));
        titleScreen.setText("Pengaturan");

        titleScreen1.setFont(new Font("Helvetica Neue", 0, 20)); // NOI18N
        titleScreen1.setForeground(new Color(2, 8, 38));
        titleScreen1.setText("Ubah Kata Sandi");

        emailTextField.setBackground(new Color(255, 255, 254));
        emailTextField.setEnabled(false);
        emailTextField.setErrorMessage("");
        emailTextField.setLabelText("Email");

        passwordField.setBackground(new Color(255, 255, 254));
        passwordField.setLabelErrorText("");
        passwordField.setLabelText("Kata Sandi Baru");
        passwordField.setValue("");

        confirmPasswordField.setBackground(new Color(255, 255, 254));
        confirmPasswordField.setLabelErrorText("");
        confirmPasswordField.setLabelText("Konfirmasi Kata Sandi Baru");
        confirmPasswordField.setValue("");

        saveBtn.setText("Simpan Password");
        saveBtn.setFont(new Font("Helvetica Neue", 1, 13)); // NOI18N

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(confirmPasswordField, GroupLayout.PREFERRED_SIZE, 630, GroupLayout.PREFERRED_SIZE))
                    .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(saveBtn, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(titleScreen)
                            .addComponent(titleScreen1)
                            .addComponent(emailTextField, GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                            .addComponent(passwordField, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(titleScreen)
                .addGap(26, 26, 26)
                .addComponent(titleScreen1)
                .addGap(18, 18, 18)
                .addComponent(emailTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(confirmPasswordField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(saveBtn, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public RoundedPasswordFieldPanel getConfirmPasswordField() {
        return confirmPasswordField;
    }

    public RoundedTextFieldPanel getEmailTextField() {
        return emailTextField;
    }

    public RoundedPasswordFieldPanel getPasswordField() {
        return passwordField;
    }

    public RoundedButton getSaveBtn() {
        return saveBtn;
    }

    public JLabel getTitleScreen() {
        return titleScreen;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RoundedPasswordFieldPanel confirmPasswordField;
    private RoundedTextFieldPanel emailTextField;
    private JTextField jTextField1;
    private RoundedPasswordFieldPanel passwordField;
    private RoundedButton saveBtn;
    private JLabel titleScreen;
    private JLabel titleScreen1;
    // End of variables declaration//GEN-END:variables
}
