/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.xyz.roemahduren.presentation.screen;

import com.xyz.roemahduren.presentation.component.ImagePanel;
import com.xyz.roemahduren.util.SwingUtil;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;

/**
 *
 * @author user
 */
public class SplashScreen extends javax.swing.JFrame {

    private int duration;

    public SplashScreen(int duration) {
        this.duration = duration;
        initComponents();
        SwingUtil.centerWindow(this);
        getContentPane().setBackground(Color.WHITE);
    }
    
    public void showSplash() {
        setVisible(true);

        Timer timer = new Timer(duration, e -> {
            setVisible(false);
            dispose();
        });
        timer.setRepeats(false);
        timer.start();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagePanel2 = new ImagePanel();
        jLabel1 = new JLabel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setBackground(null);
        setMaximumSize(new Dimension(640, 300));
        setMinimumSize(new Dimension(640, 300));
        setUndecorated(true);
        setSize(new Dimension(640, 300));

        imagePanel2.setBackground(new Color(255, 255, 255));
        imagePanel2.setImage(new ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        imagePanel2.setPreferredSize(new Dimension(300, 300));

        GroupLayout imagePanel2Layout = new GroupLayout(imagePanel2);
        imagePanel2.setLayout(imagePanel2Layout);
        imagePanel2Layout.setHorizontalGroup(imagePanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 252, Short.MAX_VALUE)
        );
        imagePanel2Layout.setVerticalGroup(imagePanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 263, Short.MAX_VALUE)
        );

        jLabel1.setFont(new Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setForeground(new Color(109, 117, 136));
        jLabel1.setText("Loading...");

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(288, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(imagePanel2, GroupLayout.PREFERRED_SIZE, 252, GroupLayout.PREFERRED_SIZE)
                        .addGap(275, 275, 275))
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(360, 360, 360))))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(imagePanel2, GroupLayout.PREFERRED_SIZE, 263, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ImagePanel imagePanel2;
    private JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
