package com.xyz.roemahduren.presentation.screen;

import com.xyz.roemahduren.presentation.component.RoundedButton;
import com.xyz.roemahduren.presentation.component.input.CheckboxPanel;
import com.xyz.roemahduren.presentation.component.input.RoundedComboBoxPanel;
import com.xyz.roemahduren.presentation.component.input.RoundedNumberFormattedFieldPanel;
import com.xyz.roemahduren.presentation.component.input.RoundedTextAreaPanel;
import com.xyz.roemahduren.presentation.component.input.RoundedTextFieldPanel;
import com.xyz.roemahduren.presentation.component.panel.RoundedPanel;
import com.xyz.roemahduren.presentation.component.table.Table;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class SupplierScreen extends javax.swing.JPanel {

    /**
     * Creates new form BranchScreen
     */
    public SupplierScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new JLabel();
        jPanel1 = new JPanel();
        supplierFormPanel = new RoundedPanel();
        nameTextField = new RoundedTextFieldPanel();
        addressTextArea = new RoundedTextAreaPanel();
        saveBtn = new RoundedButton();
        clearBtn = new RoundedButton();
        titleScreen = new JLabel();
        formPanel = new RoundedPanel();
        productNameTextField = new RoundedTextFieldPanel();
        saveBtn1 = new RoundedButton();
        clearBtn1 = new RoundedButton();
        stockNumberFormattedField = new RoundedNumberFormattedFieldPanel();
        supplierComboBox = new RoundedComboBoxPanel();
        titleTableProduct1 = new JLabel();
        jScrollPane1 = new JScrollPane();
        table1 = new Table();
        titleTableProduct = new JLabel();

        jLabel1.setFont(new Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setText("Hello Admin!");

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new Color(255, 255, 254));
        setMinimumSize(new Dimension(800, 1200));
        setPreferredSize(new Dimension(800, 1200));
        setSize(new Dimension(800, 1200));

        supplierFormPanel.setBackground(new Color(245, 245, 245));
        supplierFormPanel.setCornerRadius(8);

        nameTextField.setBackground(new Color(245, 245, 245));
        nameTextField.setLabelErrorText("");
        nameTextField.setLabelText("Nama Supplier");

        addressTextArea.setBackground(new Color(245, 245, 245));
        addressTextArea.setLabelErrorText("");
        addressTextArea.setLabelText("Alamat Supplier");

        saveBtn.setText("Simpan");
        saveBtn.setFont(new Font("Helvetica Neue", 1, 13)); // NOI18N

        clearBtn.setBackground(new Color(221, 83, 83));
        clearBtn.setText("Cear");
        clearBtn.setBorderColor(new Color(221, 83, 83));
        clearBtn.setColor(new Color(221, 83, 83));
        clearBtn.setColorClick(new Color(204, 77, 77));
        clearBtn.setColorOver(new Color(204, 77, 77));
        clearBtn.setFont(new Font("Helvetica Neue", 1, 13)); // NOI18N

        GroupLayout supplierFormPanelLayout = new GroupLayout(supplierFormPanel);
        supplierFormPanel.setLayout(supplierFormPanelLayout);
        supplierFormPanelLayout.setHorizontalGroup(supplierFormPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(supplierFormPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(supplierFormPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(supplierFormPanelLayout.createSequentialGroup()
                        .addComponent(saveBtn, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(clearBtn, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(supplierFormPanelLayout.createSequentialGroup()
                        .addGroup(supplierFormPanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addComponent(addressTextArea, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
                            .addComponent(nameTextField, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(24, 24, 24))))
        );
        supplierFormPanelLayout.setVerticalGroup(supplierFormPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(supplierFormPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(nameTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addressTextArea, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(supplierFormPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearBtn, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        titleScreen.setFont(new Font("Helvetica Neue", 1, 24)); // NOI18N
        titleScreen.setForeground(new Color(2, 8, 38));
        titleScreen.setText("Manajemen Pemasok");

        formPanel.setBackground(new Color(245, 245, 245));
        formPanel.setCornerRadius(8);

        productNameTextField.setBackground(new Color(245, 245, 245));
        productNameTextField.setLabelErrorText("");
        productNameTextField.setLabelText("Nama Produk");

        saveBtn1.setText("Simpan");
        saveBtn1.setFont(new Font("Helvetica Neue", 1, 13)); // NOI18N

        clearBtn1.setBackground(new Color(221, 83, 83));
        clearBtn1.setText("Clear");
        clearBtn1.setBorderColor(new Color(221, 83, 83));
        clearBtn1.setColor(new Color(221, 83, 83));
        clearBtn1.setColorClick(new Color(204, 77, 77));
        clearBtn1.setColorOver(new Color(204, 77, 77));
        clearBtn1.setFont(new Font("Helvetica Neue", 1, 13)); // NOI18N

        stockNumberFormattedField.setBackground(new Color(245, 245, 245));
        stockNumberFormattedField.setLabelErrorText("");
        stockNumberFormattedField.setLabelText("Stok");
        stockNumberFormattedField.setValue("0");

        supplierComboBox.setLabelErrorText("");
        supplierComboBox.setLabelText("Supplier");

        titleTableProduct1.setFont(new Font("Helvetica Neue", 0, 22)); // NOI18N
        titleTableProduct1.setForeground(new Color(2, 8, 38));
        titleTableProduct1.setText("Form Produk");

        GroupLayout formPanelLayout = new GroupLayout(formPanel);
        formPanel.setLayout(formPanelLayout);
        formPanelLayout.setHorizontalGroup(formPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(formPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(formPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(GroupLayout.Alignment.TRAILING, formPanelLayout.createSequentialGroup()
                        .addGroup(formPanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addComponent(supplierComboBox, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(formPanelLayout.createSequentialGroup()
                                .addComponent(productNameTextField, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(37, 37, 37)
                                .addComponent(stockNumberFormattedField, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(24, 24, 24))
                    .addGroup(formPanelLayout.createSequentialGroup()
                        .addGroup(formPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(titleTableProduct1)
                            .addGroup(formPanelLayout.createSequentialGroup()
                                .addComponent(saveBtn1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(clearBtn1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        formPanelLayout.setVerticalGroup(formPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, formPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(titleTableProduct1)
                .addGap(28, 28, 28)
                .addComponent(supplierComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(formPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(productNameTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(stockNumberFormattedField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn1, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearBtn1, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        table1.setModel(new DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table1);

        titleTableProduct.setFont(new Font("Helvetica Neue", 0, 22)); // NOI18N
        titleTableProduct.setForeground(new Color(2, 8, 38));
        titleTableProduct.setText("Daftar Produk Pemasok");

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleTableProduct)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleScreen)
                        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, GroupLayout.Alignment.LEADING)
                            .addComponent(formPanel, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(supplierFormPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(75, 75, 75))))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(titleScreen)
                .addGap(32, 32, 32)
                .addComponent(supplierFormPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(formPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(titleTableProduct)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 340, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public RoundedPanel getFormPanel() {
        return supplierFormPanel;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public RoundedTextFieldPanel getNameTextField() {
        return nameTextField;
    }

    public RoundedButton getSaveBtn() {
        return saveBtn;
    }

    public JLabel getTitleScreen() {
        return titleScreen;
    }

    public RoundedTextAreaPanel getAddressTextArea() {
        return addressTextArea;
    }

    public RoundedButton getClearBtn() {
        return clearBtn;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RoundedTextAreaPanel addressTextArea;
    private RoundedButton clearBtn;
    private RoundedButton clearBtn1;
    private RoundedPanel formPanel;
    private JLabel jLabel1;
    private JPanel jPanel1;
    private JScrollPane jScrollPane1;
    private RoundedTextFieldPanel nameTextField;
    private RoundedTextFieldPanel productNameTextField;
    private RoundedButton saveBtn;
    private RoundedButton saveBtn1;
    private RoundedNumberFormattedFieldPanel stockNumberFormattedField;
    private RoundedComboBoxPanel supplierComboBox;
    private RoundedPanel supplierFormPanel;
    private Table table1;
    private JLabel titleScreen;
    private JLabel titleTableProduct;
    private JLabel titleTableProduct1;
    // End of variables declaration//GEN-END:variables
}
