/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.xyz.roemahduren.presentation.component.menu;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.List;

/**
 * @author user
 */
public class SideMenu extends javax.swing.JPanel {

    private List<MenuItem> menuItems;

    /**
     * Creates new form SideMenu
     */
    public SideMenu() {
        initComponents();

        menuItems = new ArrayList<>();

        Enumeration<AbstractButton> elements = menuGroup.getElements();
        while (elements.hasMoreElements()) {
            MenuItem menuItem = (MenuItem) elements.nextElement();
            menuItems.add(menuItem);
        }
    }

    public MenuItem getMenuItem1() {
        return menuItem1;
    }

    public void setMenuItem1(MenuItem menuItem1) {
        this.menuItem1 = menuItem1;
    }

    public MenuItem getMenuItem2() {
        return menuItem2;
    }

    public void setMenuItem2(MenuItem menuItem2) {
        this.menuItem2 = menuItem2;
    }

    public MenuItem getMenuItem3() {
        return menuItem3;
    }

    public void setMenuItem3(MenuItem menuItem3) {
        this.menuItem3 = menuItem3;
    }

    public MenuItem getMenuItem4() {
        return menuItem4;
    }

    public void setMenuItem4(MenuItem menuItem4) {
        this.menuItem4 = menuItem4;
    }

    public MenuItem getMenuItem5() {
        return menuItem5;
    }

    public void setMenuItem5(MenuItem menuItem5) {
        this.menuItem5 = menuItem5;
    }

    public MenuItem getMenuItem6() {
        return menuItem6;
    }

    public void setMenuItem6(MenuItem menuItem6) {
        this.menuItem6 = menuItem6;
    }

    public MenuItem getMenuItem8() {
        return menuItem8;
    }

    public void setMenuItem8(MenuItem menuItem8) {
        this.menuItem8 = menuItem8;
    }

    public List<MenuItem> getMenuItems() {
        return menuItems;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuGroup = new ButtonGroup();
        titleLabel = new JLabel();
        menuItem1 = new com.xyz.roemahduren.presentation.component.menu.MenuItem();
        menuItem2 = new com.xyz.roemahduren.presentation.component.menu.MenuItem();
        menuItem3 = new com.xyz.roemahduren.presentation.component.menu.MenuItem();
        menuItem4 = new com.xyz.roemahduren.presentation.component.menu.MenuItem();
        menuItem5 = new com.xyz.roemahduren.presentation.component.menu.MenuItem();
        menuItem6 = new com.xyz.roemahduren.presentation.component.menu.MenuItem();
        menuItem8 = new com.xyz.roemahduren.presentation.component.menu.MenuItem();

        setBackground(new Color(61, 169, 252));
        setMinimumSize(new Dimension(306, 640));
        setPreferredSize(new Dimension(306, 640));

        titleLabel.setFont(new Font("Helvetica Neue", 0, 26)); // NOI18N
        titleLabel.setForeground(new Color(255, 255, 254));
        titleLabel.setText("Management Duren");

        menuItem1.setForeground(new Color(255, 255, 254));
        menuItem1.setIcon(new ImageIcon(getClass().getResource("/images/Dashboard.png"))); // NOI18N
        menuItem1.setText("Dashboard");
        menuItem1.setBorderColor(new Color(12, 126, 195));
        menuGroup.add(menuItem1);
        menuItem1.setColor(new Color(12, 126, 195));
        menuItem1.setColorOver(new Color(12, 126, 195));
        menuItem1.setFont(new Font("Helvetica Neue", 0, 14)); // NOI18N
        menuItem1.setHorizontalAlignment(SwingConstants.LEFT);
        menuItem1.setIconTextGap(14);

        menuItem2.setBackground(new Color(61, 169, 252));
        menuItem2.setForeground(new Color(255, 255, 254));
        menuItem2.setIcon(new ImageIcon(getClass().getResource("/images/Business.png"))); // NOI18N
        menuItem2.setText("Branch");
        menuItem2.setBorderColor(new Color(61, 169, 252));
        menuGroup.add(menuItem2);
        menuItem2.setColor(new Color(61, 169, 252));
        menuItem2.setColorOver(new Color(12, 126, 195));
        menuItem2.setFont(new Font("Helvetica Neue", 0, 14)); // NOI18N
        menuItem2.setHorizontalAlignment(SwingConstants.LEFT);
        menuItem2.setIconTextGap(14);

        menuItem3.setBackground(new Color(61, 169, 252));
        menuItem3.setForeground(new Color(255, 255, 254));
        menuItem3.setIcon(new ImageIcon(getClass().getResource("/images/Inventory.png"))); // NOI18N
        menuItem3.setText("Product");
        menuItem3.setBorderColor(new Color(61, 169, 252));
        menuGroup.add(menuItem3);
        menuItem3.setColor(new Color(61, 169, 252));
        menuItem3.setColorOver(new Color(12, 126, 195));
        menuItem3.setFont(new Font("Helvetica Neue", 0, 14)); // NOI18N
        menuItem3.setHorizontalAlignment(SwingConstants.LEFT);
        menuItem3.setIconTextGap(14);

        menuItem4.setBackground(new Color(61, 169, 252));
        menuItem4.setForeground(new Color(255, 255, 254));
        menuItem4.setIcon(new ImageIcon(getClass().getResource("/images/Category.png"))); // NOI18N
        menuItem4.setText("Category");
        menuItem4.setBorderColor(new Color(61, 169, 252));
        menuGroup.add(menuItem4);
        menuItem4.setColor(new Color(61, 169, 252));
        menuItem4.setColorOver(new Color(12, 126, 195));
        menuItem4.setFont(new Font("Helvetica Neue", 0, 14)); // NOI18N
        menuItem4.setHorizontalAlignment(SwingConstants.LEFT);
        menuItem4.setIconTextGap(14);

        menuItem5.setBackground(new Color(61, 169, 252));
        menuItem5.setForeground(new Color(255, 255, 254));
        menuItem5.setIcon(new ImageIcon(getClass().getResource("/images/Person outline.png"))); // NOI18N
        menuItem5.setText("Customer");
        menuItem5.setBorderColor(new Color(61, 169, 252));
        menuGroup.add(menuItem5);
        menuItem5.setColor(new Color(61, 169, 252));
        menuItem5.setColorOver(new Color(12, 126, 195));
        menuItem5.setFont(new Font("Helvetica Neue", 0, 14)); // NOI18N
        menuItem5.setHorizontalAlignment(SwingConstants.LEFT);
        menuItem5.setIconTextGap(14);

        menuItem6.setBackground(new Color(61, 169, 252));
        menuItem6.setForeground(new Color(255, 255, 254));
        menuItem6.setIcon(new ImageIcon(getClass().getResource("/images/Receipt long.png"))); // NOI18N
        menuItem6.setText("Transaction");
        menuItem6.setBorderColor(new Color(61, 169, 252));
        menuGroup.add(menuItem6);
        menuItem6.setColor(new Color(61, 169, 252));
        menuItem6.setColorOver(new Color(12, 126, 195));
        menuItem6.setFont(new Font("Helvetica Neue", 0, 14)); // NOI18N
        menuItem6.setHorizontalAlignment(SwingConstants.LEFT);
        menuItem6.setIconTextGap(14);

        menuItem8.setBackground(new Color(61, 169, 252));
        menuItem8.setForeground(new Color(255, 255, 254));
        menuItem8.setIcon(new ImageIcon(getClass().getResource("/images/Exit to app.png"))); // NOI18N
        menuItem8.setText("Logout");
        menuItem8.setBorderColor(new Color(61, 169, 252));
        menuGroup.add(menuItem8);
        menuItem8.setColor(new Color(61, 169, 252));
        menuItem8.setColorOver(new Color(12, 126, 195));
        menuItem8.setFont(new Font("Helvetica Neue", 0, 14)); // NOI18N
        menuItem8.setHorizontalAlignment(SwingConstants.LEFT);
        menuItem8.setIconTextGap(14);

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(menuItem1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titleLabel, GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(menuItem2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuItem3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuItem4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuItem5, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuItem6, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuItem8, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(titleLabel)
                .addGap(37, 37, 37)
                .addComponent(menuItem1, GroupLayout.PREFERRED_SIZE, 42, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menuItem2, GroupLayout.PREFERRED_SIZE, 42, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menuItem3, GroupLayout.PREFERRED_SIZE, 42, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menuItem4, GroupLayout.PREFERRED_SIZE, 42, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menuItem5, GroupLayout.PREFERRED_SIZE, 42, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menuItem6, GroupLayout.PREFERRED_SIZE, 42, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(menuItem8, GroupLayout.PREFERRED_SIZE, 42, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ButtonGroup menuGroup;
    private com.xyz.roemahduren.presentation.component.menu.MenuItem menuItem1;
    private com.xyz.roemahduren.presentation.component.menu.MenuItem menuItem2;
    private com.xyz.roemahduren.presentation.component.menu.MenuItem menuItem3;
    private com.xyz.roemahduren.presentation.component.menu.MenuItem menuItem4;
    private com.xyz.roemahduren.presentation.component.menu.MenuItem menuItem5;
    private com.xyz.roemahduren.presentation.component.menu.MenuItem menuItem6;
    private com.xyz.roemahduren.presentation.component.menu.MenuItem menuItem8;
    private JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
