/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.xyz.roemahduren.presentation.component;

import com.xyz.roemahduren.util.SwingUtil;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.net.URL;
import java.util.Enumeration;
import javax.swing.*;

/**
 * @author user
 */
public class CustomConfirmDialog extends JDialog {

    /**
     * Creates new form CustomConfirmDialog
     */

    int counter = -1;

    public CustomConfirmDialog() {
        initComponents();
        getContentPane().setBackground(new Color(0xFFFFFE));
        SwingUtil.centerWindow(this);
        setResizable(false);

        confirmBtn.addActionListener(this::confirm);
        cancelBtn.addActionListener(this::cancel);
    }

    public int showConfirmDialog(String title, String text, URL icon) {
        counter = -1;
        this.title.setText(title);
        String textHtml = String.format("<html><body>%1s</body></html>", text);
        this.text.setText(textHtml);

        if (icon != null) {
            this.icon.setImage(new ImageIcon(icon));
        }

        setModal(true);
        setVisible(true);

        return counter;
    }

    private void confirm(ActionEvent actionEvent) {
        setVisible(false);
        setModal(false);
        dispose();
        counter = 1;
    }

    private void cancel(ActionEvent actionEvent) {
        setVisible(false);
        setModal(false);
        dispose();
        counter = -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new ButtonGroup();
        icon = new ImagePanel();
        title = new JLabel();
        text = new JLabel();
        confirmBtn = new RoundedButton();
        cancelBtn = new RoundedButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new Color(255, 255, 254));
        setMaximumSize(new Dimension(600, 300));
        setMinimumSize(new Dimension(400, 200));

        icon.setBackground(new Color(255, 255, 254));
        icon.setImage(new ImageIcon(getClass().getResource("/images/Info.png"))); // NOI18N
        icon.setPreferredSize(new Dimension(48, 48));

        GroupLayout iconLayout = new GroupLayout(icon);
        icon.setLayout(iconLayout);
        iconLayout.setHorizontalGroup(iconLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );
        iconLayout.setVerticalGroup(iconLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        title.setFont(new Font("Helvetica Neue", 1, 18)); // NOI18N
        title.setForeground(new Color(2, 8, 38));
        title.setText("Title");

        text.setFont(new Font("Helvetica Neue", 0, 14)); // NOI18N
        text.setForeground(new Color(2, 8, 38));
        text.setHorizontalAlignment(SwingConstants.CENTER);
        text.setText("Text");

        confirmBtn.setForeground(new Color(255, 255, 254));
        confirmBtn.setText("Yes");
        confirmBtn.setBorderColor(new Color(140, 120, 81));
        confirmBtn.setBorderPainted(false);
        buttonGroup.add(confirmBtn);
        confirmBtn.setColor(new Color(140, 120, 81));
        confirmBtn.setColorClick(new Color(107, 92, 64));
        confirmBtn.setColorOver(new Color(124, 106, 71));

        cancelBtn.setBackground(new Color(242, 80, 66));
        cancelBtn.setForeground(new Color(255, 255, 254));
        cancelBtn.setText("Cancel");
        cancelBtn.setBorderColor(UIManager.getDefaults().getColor("Actions.Red"));
        buttonGroup.add(cancelBtn);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(title))
                    .addComponent(icon, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(text, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(confirmBtn, GroupLayout.PREFERRED_SIZE, 167, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelBtn, GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(icon, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(title)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(text)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(cancelBtn, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmBtn, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ButtonGroup buttonGroup;
    private RoundedButton cancelBtn;
    private RoundedButton confirmBtn;
    private ImagePanel icon;
    private JLabel text;
    private JLabel title;
    // End of variables declaration//GEN-END:variables
}
