/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.xyz.roemahduren.presentation.component;

import com.xyz.roemahduren.presentation.component.scroll.ScrollBar;
import com.xyz.roemahduren.util.SwingUtil;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import javax.swing.*;

/**
 *
 * @author user
 */
public class CustomDialogMessage extends javax.swing.JDialog {

    /**
     * Creates new form CustomDialogMessage
     */
    public CustomDialogMessage() {
        initComponents();
        getContentPane().setBackground(new Color(0xFFFFFE));
        SwingUtil.centerWindow(this);
        setResizable(false);
        SwingUtil.fixScroll(scroll);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        image = new ImagePanel();
        title = new JLabel();
        okBtn = new RoundedButton();
        scroll = new JScrollPane();
        text = new JLabel();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        setFont(new Font("Helvetica Neue", 0, 13)); // NOI18N
        setMaximumSize(new Dimension(600, 300));
        setMinimumSize(new Dimension(400, 200));
        setResizable(false);
        setSize(new Dimension(400, 200));

        image.setBackground(new Color(255, 255, 254));
        image.setImage(new ImageIcon(getClass().getResource("/images/Warning.png"))); // NOI18N

        GroupLayout imageLayout = new GroupLayout(image);
        image.setLayout(imageLayout);
        imageLayout.setHorizontalGroup(imageLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );
        imageLayout.setVerticalGroup(imageLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        title.setFont(new Font("Helvetica Neue", 1, 18)); // NOI18N
        title.setForeground(new Color(2, 8, 38));
        title.setHorizontalAlignment(SwingConstants.CENTER);
        title.setText("Warning");
        title.setVerticalAlignment(SwingConstants.TOP);

        okBtn.setBackground(new Color(130, 148, 96));
        okBtn.setForeground(new Color(255, 255, 254));
        okBtn.setText("Ok");
        okBtn.setBorderColor(new Color(130, 148, 96));
        okBtn.setBorderPainted(false);
        okBtn.setColor(new Color(130, 148, 96));
        okBtn.setColorClick(new Color(108, 122, 80));
        okBtn.setColorOver(new Color(118, 134, 87));
        okBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });

        text.setFont(new Font("Helvetica Neue", 0, 14)); // NOI18N
        text.setForeground(new Color(2, 8, 38));
        text.setHorizontalAlignment(SwingConstants.CENTER);
        text.setText("Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.  ");
        text.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        text.setHorizontalTextPosition(SwingConstants.CENTER);
        scroll.setViewportView(text);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(scroll, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(title, GroupLayout.PREFERRED_SIZE, 347, GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(okBtn, GroupLayout.PREFERRED_SIZE, 225, GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(image, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(image, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(title, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scroll, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(okBtn, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        setVisible(false);
        setModal(false);
        dispose();
    }//GEN-LAST:event_okBtnActionPerformed

    public void showMessageDialog(String title, String text, URL imageSource) {
        this.title.setText(title);
        String html = "<html><body>%1s</body></html>";
        String htmlFormat = String.format(html, text);
        this.text.setText(htmlFormat);

        if (imageSource != null) {
            this.image.setImage(new ImageIcon(imageSource));
        }

        setVisible(true);
        setModal(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ImagePanel image;
    private RoundedButton okBtn;
    private JScrollPane scroll;
    private JLabel text;
    private JLabel title;
    // End of variables declaration//GEN-END:variables
}
