/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.xyz.roemahduren.presentation.component.input;

import java.awt.Color;
import java.awt.Font;
import javax.swing.GroupLayout;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.LayoutStyle;

/**
 * @author user
 */
public class CheckboxPanel extends JPanel {

    /**
     * Creates new form CheckboxPanel
     */
    public CheckboxPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label = new JLabel();
        errorLabel = new JLabel();
        checkbox = new JCheckBox();

        label.setFont(new Font("Helvetica Neue", 0, 14)); // NOI18N
        label.setForeground(new Color(95, 108, 123));
        label.setText("label");

        errorLabel.setFont(new Font("Helvetica Neue", 0, 14)); // NOI18N
        errorLabel.setForeground(new Color(220, 53, 69));
        errorLabel.setText("error");

        checkbox.setFont(new Font("Helvetica Neue", 0, 14)); // NOI18N
        checkbox.setForeground(new Color(95, 108, 123));
        checkbox.setText("jCheckBox1");
        checkbox.setName(""); // NOI18N

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(label)
                    .addComponent(checkbox)
                    .addComponent(errorLabel))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(label)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkbox)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public JCheckBox getCheckbox() {
        return checkbox;
    }

    public void setCheckbox(JCheckBox checkbox) {
        this.checkbox = checkbox;
    }

    public String getErrorLabel() {
        return errorLabel.getText();
    }

    public void setErrorLabel(String errorLabel) {
        this.errorLabel.setText(errorLabel);
    }

    public boolean getValue() {
        return this.checkbox.isSelected();
    }

    public void setValue(boolean value) {
        this.checkbox.setSelected(value);
    }

    public String getLabel() {
        return label.getText();
    }

    public void setLabel(String label) {
        this.label.setText(label);
    }

    public void getText() {
        this.checkbox.getText();
    }

    public void setText(String text) {
        this.checkbox.setText(text);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JCheckBox checkbox;
    private JLabel errorLabel;
    private JLabel label;
    // End of variables declaration//GEN-END:variables
}
