/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.xyz.roemahduren.presentation.component.input;

import java.awt.Color;
import javax.swing.GroupLayout;
import javax.swing.JLabel;
import javax.swing.LayoutStyle;

/**
 *
 * @author user
 */
public class RoundedTextFieldPanel extends javax.swing.JPanel {

    /**
     * Creates new form RoundedTextFieldV2
     */
    public RoundedTextFieldPanel() {
        initComponents();
    }

    public String getLabelText() {
        return label.getText();
    }

    public void setLabelText(String text) {
        this.label.setText(text);
    }

    public String getLabelErrorText() {
        return errorLabel.getText();
    }

    public void setLabelErrorText(String text) {
        this.errorLabel.setText(text);
    }


    public String getPlaceholder() {
        return textField.getPlaceholder();
    }

    public void setPlaceholder(String text) {
        this.textField.setPlaceholder(text);
    }


    public JLabel getErrorLabel() {
        return errorLabel;
    }

    public JLabel getLabel() {
        return label;
    }

    public String getValue() {
        return textField.getText();
    }

    public void setValue(String text) {
        this.textField.setText(text);
    }

    public String getErrorMessage() {
        return this.errorLabel.getText();
    }

    public void setErrorMessage(String text) {
        this.errorLabel.setText(text);
    }

    public void clearErrorMessage() {
        this.errorLabel.setText("");
    }

    public RoundedTextField getTextField() {
        return textField;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField = new RoundedTextField();
        label = new JLabel();
        errorLabel = new JLabel();

        textField.setText("roundedTextField1");

        label.setForeground(new Color(95, 108, 123));
        label.setText("label");

        errorLabel.setForeground(new Color(220, 53, 69));
        errorLabel.setText("error");

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(errorLabel)
                    .addComponent(label)
                    .addComponent(textField, GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(label)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textField, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel errorLabel;
    private JLabel label;
    private RoundedTextField textField;
    // End of variables declaration//GEN-END:variables
}
