package com.xyz.roemahduren.presentation.component.dialog;

import com.xyz.roemahduren.application.controller.MainController;
import com.xyz.roemahduren.constant.CustomDialog;
import com.xyz.roemahduren.domain.model.response.OrderDetailResponse;
import com.xyz.roemahduren.domain.service.ReportService;
import com.xyz.roemahduren.exception.NotFoundException;
import com.xyz.roemahduren.util.ServiceWorker;
import com.xyz.roemahduren.util.SwingUtil;

import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.util.List;

public class DetailTransactionHistoryDialog extends javax.swing.JDialog {

    private final ReportService service;
    private final CustomDialog dialog;
    private List<OrderDetailResponse> orderDetailResponses;
    private String orderId;

    public DetailTransactionHistoryDialog(ReportService service, CustomDialog dialog) {
        this.service = service;
        this.dialog = dialog;
        initComponents();
        getContentPane().setBackground(new Color(255, 255, 254));
        SwingUtil.centerWindow(this);
        SwingUtil.fixScroll(orderDetailScrollPane);
        closeButton.addActionListener(this::closeDialog);
        printBtn.addActionListener(this::printInvoice);
    }

    private void printInvoice(ActionEvent actionEvent) {
        new ServiceWorker<>(
                () -> {
                    SwingUtil.setLoading(this.printBtn);
                    service.generateInvoice(orderId, MainController.user.getEmail());
                    return true;
                },
                aBoolean -> {
                },
                throwable -> dialog.getFailedMessageDialog(throwable.getMessage()),
                () -> SwingUtil.clearPrimaryLoading(this.printBtn, "Print Invoice")
        ).execute();
    }

    public void showDialog(List<OrderDetailResponse> orderDetailResponse) {
        setOrderDetailResponses(orderDetailResponse);
        initTable();
        setModal(true);
        setVisible(true);
    }

    public void closeDialog(ActionEvent actionEvent) {
        setVisible(false);
        setModal(false);
        dispose();
    }

    public void setOrderDetailResponses(List<OrderDetailResponse> orderDetailResponses) {
        if (orderDetailResponses.isEmpty()) {
            throw new NotFoundException(NotFoundException.ORDER_NOT_FOUND);
        }
        this.orderDetailResponses = orderDetailResponses;
    }

    private void initTable() {
        String[] HEADERS = {"#", "Nama Produk", "Kuantitas", "Total Harga"};
        DefaultTableModel model = new DefaultTableModel(null, HEADERS);
        orderDetailTable.setModel(model);

        int counter = 1;
        for (OrderDetailResponse orderDetailResponse : orderDetailResponses) {
            model.addRow(new Object[]{
                    counter++,
                    orderDetailResponse.getProductName(),
                    orderDetailResponse.getQuantity(),
                    orderDetailResponse.getTotalPrice()
            });
            orderId = orderDetailResponse.getOrderId();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleScreen = new javax.swing.JLabel();
        printBtn = new com.xyz.roemahduren.presentation.component.RoundedButton();
        orderDetailScrollPane = new javax.swing.JScrollPane();
        orderDetailTable = new com.xyz.roemahduren.presentation.component.table.Table();
        closeButton = new com.xyz.roemahduren.presentation.component.RoundedButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Detail Transaksi");
        setBackground(new java.awt.Color(245, 245, 245));
        setMaximumSize(new java.awt.Dimension(1280, 800));
        setMinimumSize(new java.awt.Dimension(600, 500));
        setSize(new java.awt.Dimension(600, 500));

        titleScreen.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        titleScreen.setForeground(new java.awt.Color(2, 8, 38));
        titleScreen.setText("Detail Transaksi");

        printBtn.setBackground(new java.awt.Color(221, 83, 83));
        printBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Print.png"))); // NOI18N
        printBtn.setText("Print Invoice");
        printBtn.setBorderColor(new java.awt.Color(221, 83, 83));
        printBtn.setColor(new java.awt.Color(221, 83, 83));
        printBtn.setColorClick(new java.awt.Color(204, 77, 77));
        printBtn.setColorOver(new java.awt.Color(204, 77, 77));
        printBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N

        orderDetailTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String[]{
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        orderDetailScrollPane.setViewportView(orderDetailTable);

        closeButton.setText("Tutup");
        closeButton.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(orderDetailScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(titleScreen)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(printBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(titleScreen)
                                        .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addComponent(printBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(orderDetailScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.xyz.roemahduren.presentation.component.RoundedButton closeButton;
    private javax.swing.JScrollPane orderDetailScrollPane;
    private com.xyz.roemahduren.presentation.component.table.Table orderDetailTable;
    private com.xyz.roemahduren.presentation.component.RoundedButton printBtn;
    private javax.swing.JLabel titleScreen;
    // End of variables declaration//GEN-END:variables
}
